# Site settings
title: Dimsmary
header-img: "img/ele_1.jpg"
tagline: ""  
description: "Do What U Wanna Do"  
baseurl: ""
# url: "http://localhost:4000"
# enforce_ssl: 

# About/contact
owner: 
  name: "Dimsmary"
  email: realdimsmary@gmail.com
  bio: ""

# Data

# gavatar: 
favicon: img/favicon.ico
github_username: Dimsmary 
weibo_username: 低能技术缝合师

# Build settings  

# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-paginate
# - jekyll-gallery-generator 
permalink: none
paginate: 9
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dimsmary"
      header-img: "img/ele_1_c.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : disqus
  disqus :
      short_name : Dimsmary

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
